routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Administrator\LogController;
use App\Http\Controllers\Administrator\RoleController;
use App\Http\Controllers\Administrator\ProductController;
use App\Http\Controllers\Administrator\ProfileController;
use App\Http\Middleware\AdminLoginMiddleware;

use App\Http\Controllers\Administrator\DashboardController;
use App\Http\Controllers\Administrator\UserAdminController;
use App\Http\Controllers\Administrator\PermissionController;
use App\Http\Controllers\Administrator\NotificationController;

use App\Http\Controllers\Administrator\AdminLogableController;
use App\Http\Controllers\Administrator\PublicStorageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('administrator.login');
});

Route::group([
    'prefix' => config('admin.prefix', 'administrator'),
    'as' => 'administrator.'
], function() {

    Route::group([
        'namespace' => 'App\Http\Controllers\Administrator',
    ], function () {
        Auth::routes(['register' => false]);
    });

    Route::group([
        'middleware' => [AdminLoginMiddleware::class],
    ], function () {
        Route::resource('/storage', PublicStorageController::class)->only(['index']);

        Route::resource('/', DashboardController::class)->only(['index']);
        Route::resource('/notification', NotificationController::class)->only(['index', 'show', 'store']);
        Route::resource('/profile', ProfileController::class)->only(['index', 'store']);

        Route::resource('/products', ProductController::class);

        Route::group(['as' => 'account.', 'prefix' => 'account'], function () {
            Route::resource('/admin', UserAdminController::class);
        });

        Route::group(['as' => 'system.', 'prefix' => 'system'], function () {
            Route::resource('/log', LogController::class)->only(['index']);
            Route::resource('/activity', AdminLogableController::class)->only(['index', 'destroy']);
        });

        Route::group(['as' => 'access.', 'prefix' => 'access'], function () {
            Route::resource('/role', RoleController::class);
            Route::resource('/permission', PermissionController::class)->only(['index', 'show', 'update']);
        });

    });
});

resources/views/template/logable/_button_delete.blade.php
@can(['administrator.system.activity.delete'])
<a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#moda-confirmation">
  Delete
</a>

<div class="modal fade" id="moda-confirmation" tabindex="-1" aria-labelledby="moda-confirmationLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header border-0">
        <h5 class="modal-title" id="moda-confirmationLabel">Delete Log</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Due you want to Delete data older than {{ config('admin.log_activity_life', 7) }} days?
      </div>
      <div class="modal-footer border-0">
        <form method="POST" id="form-delete-older-actifity" action="{{ route('administrator.system.activity.destroy', 0) }}">
          @csrf
          @method('DELETE')
          <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
          <button type="submit" class="btn btn-primary">Yes</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endcan

resources/views/template/logable/_table_buttons.blade.php
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal-detail-activity-{{ $item->id }}">
  Show
</button>

<div class="modal text-left fade" id="modal-detail-activity-{{ $item->id }}" tabindex="-1" aria-labelledby="modal-detail-activity-{{ $item->id }}Label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header border-0">
        <h5 class="modal-title" id="modal-detail-activity-{{ $item->id }}Label">Activity</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr>
              <td colspan="2">
                <p class="card-title font-weight-bold my-2">User Account</p>
              </td>
            </tr>
            <tr>
              <td>Date</td>
              <td>{{ $item->created_at->format('d/m/y H:i') }} - {{ $item->created_at->diffForHumans() }}</td>
            </tr>
            <tr>
              <td>Name</td>
              <td>{{ $item->user->name }}</td>
            </tr>
            <tr>
              <td>Email</td>
              <td>{{ $item->user->email }}</td>
            </tr>

            <tr>
              <td>Event Type</td>
              <td>
                <span class="badge badge-{{ $item->colors[$item->type] ?? 'warning' }}">
                  {{ ucwords($item->type) }}
                </span>
              </td>
            </tr>

            <tr>
              <td>Model</td>
              <td>{{ ucwords($item->logable_type) }}</td>
            </tr>
            <tr>
              <td>ID</td>
              <td>{{ ucwords($item->logable_id) }}</td>
            </tr>
            <tr>
              <td colspan="2">
                <p class="card-title font-weight-bold my-2">New Data</p>
              </td>
            </tr>

            @foreach ((Array) $item->new_data as $field => $data)
            @php
                $new = is_array($data) ? json_encode($data) : $data;
                $old = isset($item->old_data[$field]) ? is_array($item->old_data[$field]) ? json_encode($item->old_data[$field]) : $item->old_data[$field] : $new
            @endphp
                <tr>
                  <td>{{ $field }}</td>
                  <td class="{{ ($old === $new) ? '' : 'text-danger' }}">{!!  $new !!}</td>
                </tr>
            @endforeach

            <tr>
              <td colspan="2">
                <p class="card-title font-weight-bold my-2">Old Data</p>
              </td>
            </tr>

            @forelse ((Array) $item->old_data as $field => $data)
              @php
                  $old = is_array($data) ? json_encode($data) : $data;
                  $new = isset($item->new_data[$field]) ? is_array($item->new_data[$field]) ? json_encode($item->new_data[$field]) : $item->new_data[$field] : $old
              @endphp
                <tr>
                  <td>{{ $field }}</td>
                  <td class="{{ ($old === $new) ? '' : 'text-warning' }}">{!!  $old !!}</td>
                </tr>
                @empty 
                <tr>
                  <td colspan="2">No data available</td>
                </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>