routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Administrator\LogController;
use App\Http\Controllers\Administrator\RoleController;
use App\Http\Controllers\Administrator\ProductController;
use App\Http\Controllers\Administrator\ProfileController;
use App\Http\Middleware\AdminLoginMiddleware;

use App\Http\Controllers\Administrator\DashboardController;
use App\Http\Controllers\Administrator\UserAdminController;
use App\Http\Controllers\Administrator\PermissionController;
use App\Http\Controllers\Administrator\NotificationController;

use App\Http\Controllers\Administrator\AdminLogableController;
use App\Http\Controllers\Administrator\PublicStorageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('administrator.login');
});

Route::group([
    'prefix' => config('admin.prefix', 'administrator'),
    'as' => 'administrator.'
], function() {

    Route::group([
        'namespace' => 'App\Http\Controllers\Administrator',
    ], function () {
        Auth::routes(['register' => false]);
    });

    Route::group([
        'middleware' => [AdminLoginMiddleware::class],
    ], function () {
        Route::resource('/storage', PublicStorageController::class)->only(['index']);

        Route::resource('/', DashboardController::class)->only(['index']);
        Route::resource('/notification', NotificationController::class)->only(['index', 'show', 'store']);
        Route::resource('/profile', ProfileController::class)->only(['index', 'store']);

        Route::resource('/products', ProductController::class);

        Route::group(['as' => 'account.', 'prefix' => 'account'], function () {
            Route::resource('/admin', UserAdminController::class);
        });

        Route::group(['as' => 'system.', 'prefix' => 'system'], function () {
            Route::resource('/log', LogController::class)->only(['index']);
            Route::resource('/activity', AdminLogableController::class)->only(['index', 'destroy']);
        });

        Route::group(['as' => 'access.', 'prefix' => 'access'], function () {
            Route::resource('/role', RoleController::class);
            Route::resource('/permission', PermissionController::class)->only(['index', 'show', 'update']);
        });

    });
});

app/Models/AdminTrait.php
<?php

namespace App\Models;

use App\Models\Role;
use App\Models\AdminLogable;
use App\Notifications\ResetPasswordNotification;
use App\Exceptions\AdminException;

trait AdminTrait {

  /**
   * Roles
   *
   * @return Collection
   */
  public function roles() {
    return $this->belongsToMany(Role::class, 'admin_role_user', 'user_id', 'role_id', 'id', 'id');
  }

  /**
   * Get role first
   *
   * @return Collection
   */
  public function getRoleAttribute() {
    return $this->roles()->first();
  }

  /**
   * List of permissions
   *
   * @return void
   */
  public function getPermissionAttribute() {
    $permissions = [];
    foreach($this->roles as $role) {
      $gates = $role->gates ?? [];
      foreach($gates as $gate) {
        if(!in_array($gate, $permissions)) {
          $permissions[] = $gate;
        }
      }
    }
    return $permissions;
  }

  /**
   * Send the password reset notification.
   *
   * @param  string  $token
   * @return void
   */
  public function sendPasswordResetNotification($token) {
    $this->notify(new ResetPasswordNotification($token, $this->email));
  }


  /**
   * Relation to activity log
   */
  public function activities() {
    return $this->hasMany(AdminLogable::class, 'user_id', 'id');
  }

  /**
   * Gravatar
   */
    public function getGravatarUrlAttribute() {
      $grav_url = "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $this->email ) ) ) . "&s=100";
      return isset($this->avatar_url) ? $this->avatar_url : $grav_url;
    }

}

resources/views/template/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ config('app.name') }} | Administrator</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta name="robots" content="noindex,nofollow">
  <link rel="stylesheet" href="{{ asset('/css/admin/app.css') }}">

  {!! $styles ?? null !!}

</head>
<body>

  <div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm p-0">
      <a class="navbar-brand mr-0 p-3" href="{{ route('administrator.index') }}">
        @if (config('admin.logo'))
          <img src="{{ config('admin.logo') }}" alt="Logo" width="120">
        @else
          {{ config('app.name') }}
        @endif
      </a>

      <ul class="navbar-nav mr-auto">
        <li>
          <button class="border-0 btn btn-link admin-sidebar-toggle" type="button">
            {!! admin()->icon('menu') !!}
          </button>
          <span class="admin-greating">Hi, {{ Str::limit($adminUser->name, 10) }} <small class="text-muted">/ {{ $adminUser->role->name }}</small></span>
        </li>
      </ul>

      <ul class="admin-navbar-nav d-flex align-items-center justify-content-center ml-auto pr-3">
          <x-template-notification />
          <li class="nav-item dropdown">

            <a id="navbarDropdown" class="nav-link dropdown-toggle pl-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
              <img src="{{ $adminUser->gravatar_url }}" alt="Avatar" class="img-thumbnail rounded-circle" width="40">
            </a>

            <ul style="right:0;" class="dropdown-menu mt-2 rounded shadow-sm dropdown-menu-right admin-top-menu" aria-labelledby="navbarDropdown">
                <li class="admin-top-menu-body">
                  <x-template-toprightmenu />
                </li>
            </ul>
        </li>
      </ul>
    </nav>

    <div class="admin-container">
      <aside class="admin-sidebar">
        <strong class="ml-3">Main Menus</strong>
        <x-template-sidebar />
      </aside>

      <div class="admin-content">
        <div class="col-lg-12">
          <x-template-alert />
        </div>
        <div class="admin-page-title">
          <div class="col-lg-12" style="position: relative;">

            <div class="row">
              <div class="col-lg-6 position-relative align-middle">
                <h4 class="d-inline-block mr-2">
                  @if(request()->has('back'))
                    <a href="{{ request()->get('back') }}" class="btn btn-outline-primary btn-sm mr-1 px-3">&larr;</a>
                  @endif
                  {!! $title ?? 'Title Page' !!}
                </h4>
                {{ $buttons ?? null }}

              </div>
              <div class="col-lg-6 breadcrumb-container">
                <x-template-breadcrumb />
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-12">

          {{ $slot }}

        </div>

      </div>
      <footer class="admin-footer py-3 bg-white">
        @include('administrator.footer')
      </footer>

    </div>

  </div>

  <script src="{{ asset('/js/admin/app.js') }}"></script>

  {!! $scripts ?? null !!}

</body>
</html>

resources/views/template/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ config('app.name') }} | Auth</title>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta name="robots" content="noindex,nofollow">
  <link rel="stylesheet" href="{{ asset('/css/admin/app.css') }}">
</head>
<body>

  <div id="app">
    @yield('content')
  </div>

  <script src="{{ asset('/js/admin/app.js') }}"></script>
</body>
</html>